"""Detection signals and (later) confidence scoring.

Milestone 3 implements Signal 1 only — the Groq LLM classifier — plus a helper
that maps a single AI-likelihood score to an attribution result. Signal 2
(stylometrics) and the real combined scoring arrive in Milestone 4; the
thresholds defined here are the same ones that scoring will reuse.
"""

import json
import os
import re
import statistics
import string

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

# Signal weights for the combined confidence score.
# Three-way ensemble (stretch: ensemble detection). The LLM stays dominant;
# stylometrics and the lexical "AI-tell" heuristic corroborate. Weights sum to 1.
LLM_WEIGHT = 0.55
STYLOMETRIC_WEIGHT = 0.25
LEXICAL_WEIGHT = 0.20

# Attribution thresholds — see planning.md > Uncertainty Representation.
# Asymmetric on purpose: it takes strong evidence (>=0.70) to call something AI,
# while the wide "uncertain" band absorbs borderline cases to avoid false
# positives against human writers.
AI_THRESHOLD = 0.70
HUMAN_THRESHOLD = 0.40

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


LLM_SYSTEM_PROMPT = (
    "You are an AI-content detector for a creative-writing platform. "
    "Given a passage, estimate the probability that it was generated by an AI "
    "language model rather than written by a human. Weigh semantic coherence, "
    "specificity of lived detail, idiom, hedging patterns, and the averaged-out "
    "'generic' voice typical of AI text. "
    "Respond ONLY with a compact JSON object of the exact form "
    '{"ai_likelihood": <float between 0 and 1>, "reasoning": "<one short sentence>"}. '
    "0.0 means clearly human-written, 1.0 means clearly AI-generated. "
    "Give a calibrated probability, not a rounded 0 or 1. Output no other text."
)

# Image-metadata variant (stretch: multi-modal support). Same JSON contract,
# but framed for serialized metadata describing an image rather than prose.
LLM_IMAGE_PROMPT = (
    "You are an AI-content detector for a creative platform. The input is "
    "structured metadata describing an image (title, medium, tags, and a "
    "creator-written description). Estimate the probability that this metadata "
    "and description were AI-generated rather than written by a human creator. "
    "Weigh genericness, vague boilerplate phrasing, and lack of specific, "
    "personal artistic intent. "
    "Respond ONLY with a compact JSON object of the exact form "
    '{"ai_likelihood": <float between 0 and 1>, "reasoning": "<one short sentence>"}. '
    "0.0 means clearly human-written, 1.0 means clearly AI-generated. "
    "Give a calibrated probability, not a rounded 0 or 1. Output no other text."
)


def llm_signal(text, mode="text"):
    """Signal 1: ask a Groq-hosted LLM how AI-generated the text looks.

    `mode` selects the system prompt: "text" for prose, "image_metadata" for
    serialized image metadata (stretch: multi-modal support).

    Returns {"llm_score": float in [0, 1], "reasoning": str}. On any failure
    (network, parsing, missing key) it degrades to a neutral 0.5 and reports the
    reason, so a signal outage never crashes a submission (see planning.md).
    """
    system_prompt = LLM_IMAGE_PROMPT if mode == "image_metadata" else LLM_SYSTEM_PROMPT
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(response.choices[0].message.content)
        score = max(0.0, min(1.0, float(data["ai_likelihood"])))
        reasoning = str(data.get("reasoning", "")).strip()
        return {"llm_score": score, "reasoning": reasoning}
    except Exception as exc:  # degrade gracefully rather than 500 the request
        return {"llm_score": 0.5, "reasoning": f"LLM signal unavailable: {exc}"}


def attribution_from_score(score):
    """Map an AI-likelihood score to an attribution result.

    Milestone 3 applies this to the single LLM score as a placeholder; from
    Milestone 4 the same thresholds apply to the combined confidence score.
    """
    if score >= AI_THRESHOLD:
        return "likely_ai"
    if score < HUMAN_THRESHOLD:
        return "likely_human"
    return "uncertain"


def _clamp(value, low=0.0, high=1.0):
    return max(low, min(high, value))


# Stylometric sub-metric weights (sum to 1.0) — see planning.md.
_VARIANCE_WEIGHT = 0.50
_TTR_WEIGHT = 0.25
_PUNCT_WEIGHT = 0.25

# Distinct punctuation characters we count toward "variety".
_PUNCTUATION = set(string.punctuation) | {"—", "–", "“", "”", "‘", "’"}


def stylometric_signal(text):
    """Signal 2: structural uniformity heuristics (pure Python).

    Returns a dict with the combined `stylometric_score` in [0, 1] (higher =
    more AI-like), the three raw metrics, and a `reliable` flag. AI text tends
    to be uniform; human writing tends to be variable. Each metric is mapped to
    an AI-likelihood sub-score using the directions documented in planning.md.

    On text shorter than 3 sentences the statistics are too noisy to trust, so
    the signal returns a neutral 0.5 and flags low reliability.
    """
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    tokens = re.findall(r"[a-z']+", text.lower())

    if len(sentences) < 3 or len(tokens) < 5:
        return {
            "stylometric_score": 0.5,
            "reliable": False,
            "metrics": {
                "sentence_length_sd": None,
                "type_token_ratio": None,
                "distinct_punctuation": None,
            },
        }

    # 1. Sentence-length variance: low variance = uniform = AI.
    sentence_lengths = [len(s.split()) for s in sentences]
    length_sd = statistics.pstdev(sentence_lengths)
    v_score = _clamp(1 - length_sd / 8)

    # 2. Type-token ratio: high, evenly-spread vocabulary = AI rarely repeats.
    ttr = len(set(tokens)) / len(tokens)
    t_score = _clamp((ttr - 0.5) / 0.3)

    # 3. Punctuation variety: few distinct types = regular/clean = AI.
    distinct_punct = len({ch for ch in text if ch in _PUNCTUATION})
    p_score = _clamp(1 - distinct_punct / 5)

    stylometric_score = (
        _VARIANCE_WEIGHT * v_score
        + _TTR_WEIGHT * t_score
        + _PUNCT_WEIGHT * p_score
    )

    return {
        "stylometric_score": _clamp(stylometric_score),
        "reliable": True,
        "metrics": {
            "sentence_length_sd": round(length_sd, 3),
            "type_token_ratio": round(ttr, 3),
            "distinct_punctuation": distinct_punct,
        },
    }


# Lexical "AI-tell" markers (stretch: ensemble detection). Stock phrases and
# transition words over-represented in LLM output. This is the weakest, most
# easily-gamed signal — hence the lowest weight — but it adds an independent
# *lexical* property distinct from the LLM's semantics and stylometric structure.
_AI_TELL_PHRASES = [
    "it is important to note", "it's important to note", "it is worth noting",
    "in conclusion", "in summary", "furthermore", "moreover", "delve into",
    "navigate the complexities", "navigate the intricacies", "in today's world",
    "in the realm of", "plays a crucial role", "plays a vital role",
    "plays a significant role", "a testament to", "rich tapestry",
    "ever-evolving", "ever-changing landscape", "underscores the importance",
    "it is essential to", "it is equally", "paradigm shift", "in the digital age",
    "when it comes to", "the world of", "foster a", "leverage",
]


def lexical_signal(text):
    """Signal 3 (stretch): rate of AI-associated stock phrases and em-dashes.

    Returns {"lexical_score": float in [0, 1], "markers": int}, where higher
    means more AI-like. The score is the marker rate per 100 words, scaled so
    ~6 markers per 100 words saturates at 1.0.
    """
    lower = text.lower()
    phrase_hits = sum(lower.count(phrase) for phrase in _AI_TELL_PHRASES)
    em_dashes = text.count("—")
    markers = phrase_hits + em_dashes

    words = max(len(text.split()), 1)
    rate_per_100 = markers * 100 / words
    lexical_score = _clamp(rate_per_100 / 6)
    return {"lexical_score": lexical_score, "markers": markers}


def combine_scores(llm_score, stylometric_score, lexical_score):
    """Blend the three signals into one calibrated confidence score (P(AI)).

    Three-way ensemble (stretch: ensemble detection):
      base         = 0.55*llm + 0.25*stylometric + 0.20*lexical
      spread       = max(signals) - min(signals)      # generalized disagreement
      confidence   = base - (base - 0.5) * (0.5 * spread)

    The spread term pulls the score toward the uncertain midpoint (0.5) when the
    signals conflict, so a lone dissenting signal still widens uncertainty
    instead of producing a falsely confident verdict.
    """
    base = (
        LLM_WEIGHT * llm_score
        + STYLOMETRIC_WEIGHT * stylometric_score
        + LEXICAL_WEIGHT * lexical_score
    )
    spread = max(llm_score, stylometric_score, lexical_score) - min(
        llm_score, stylometric_score, lexical_score
    )
    confidence = base - (base - 0.5) * (0.5 * spread)
    return _clamp(confidence)


if __name__ == "__main__":
    # Calibration harness — run `python detection.py` to inspect both signals
    # and the combined score across the four spec test inputs before trusting
    # the endpoint. Prints signals separately so a misbehaving one is visible.
    from dotenv import load_dotenv

    load_dotenv()
    samples = {
        "clearly AI": (
            "Artificial intelligence represents a transformative paradigm shift "
            "in modern society. It is important to note that while the benefits "
            "of AI are numerous, it is equally essential to consider the ethical "
            "implications. Furthermore, stakeholders across various sectors must "
            "collaborate to ensure responsible deployment."
        ),
        "clearly human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium "
            "in it and i was thirsty for like three hours after. my friend got "
            "the spicy version and said it was better. probably won't go back "
            "unless someone drags me there"
        ),
        "borderline: formal human": (
            "The relationship between monetary policy and asset price inflation "
            "has been extensively studied in the literature. Central banks face "
            "a fundamental tension between their mandate for price stability and "
            "the unintended consequences of prolonged low interest rates on "
            "equity and real estate valuations."
        ),
        "borderline: lightly edited AI": (
            "I've been thinking a lot about remote work lately. There are genuine "
            "tradeoffs — flexibility and no commute on one side, isolation and "
            "blurred work-life boundaries on the other. Studies show productivity "
            "varies widely by individual and role type."
        ),
    }
    for name, sample in samples.items():
        llm = llm_signal(sample)
        stylo = stylometric_signal(sample)
        lex = lexical_signal(sample)
        combined = combine_scores(
            llm["llm_score"], stylo["stylometric_score"], lex["lexical_score"]
        )
        print(f"[{name}]")
        print(f"   llm_score        = {llm['llm_score']:.3f}  ({llm['reasoning']})")
        print(f"   stylometric_score= {stylo['stylometric_score']:.3f}  "
              f"(reliable={stylo['reliable']}, metrics={stylo['metrics']})")
        print(f"   lexical_score    = {lex['lexical_score']:.3f}  "
              f"(markers={lex['markers']})")
        print(f"   combined         = {combined:.3f}  -> "
              f"{attribution_from_score(combined)}\n")
